### ISSUE TITLE
peer to peer code review 

### ISSUE THREAD

**Issue by gedewon** [acolombo1/Capstone1#3]
## It looks really nice !!! 

a couple of suggestions
1. kindly add an h1 tag in your document  
2. kindly use section instead of div or make the higher-level section and use div within it 
3. watch out for the use of the hr tag on your page 

Thank you look Great !!

**Comment by acolombo1** [comment]
Implemented 1 and 2. I see it practical to continue using hr, borders are not a good replacement.
